apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tharunsubu/calculator.git
    targetRevision: main
    path: argocd   # This folder should contain deployment.yaml, service.yaml, etc.
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
