apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator
  namespace: argocd   # ArgoCD namespace
spec:
  project: default

  source:
    repoURL: 'https://github.com/tharunsubu/calculator.git'   # your Helm repo
    targetRevision: main        # branch or tag
    path: helm            # path to chart in repo
    helm:
      releaseName: calculator
      values: |
        replicaCount: 2
        service:
          type: ClusterIP
          port: 80

  destination:
    server: https://kubernetes.default.svc
    namespace: calculator       # app namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
