apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  namespace: web 
  labels:
    app: calculator
spec:
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Change to LoadBalancer if you want external access
