apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculator.fullname" . }}
  labels:
    {{- include "calculator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "calculator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calculator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "nginx:stable"   # ✅ nginx serves a webpage
          ports:
            - containerPort: 80
