apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculator.fullname" . }}
  labels:
    {{- include "calculator.labels" . | nindent 4 }}
spec:
  type: NodePort   # ✅ for Minikube
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # Fixed port for easy access
  selector:
    {{- include "calculator.selectorLabels" . | nindent 4 }}
